version: "3.8"

services:
  backend:
    build: ./backend
    command: uvicorn app.app:app --reload --host 0.0.0.0 --port 8000
    restart: always
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432
    depends_on:
      - db
    volumes:
      - ./backend/app/:/app/
    ports:
      - 8000:8000

  db:
    image: postgres:12.0-alpine
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    volumes:
      - postgres:/var/lib/postgresql/data/

volumes:
  postgres: